version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres-data:/var/lib/postgresql/data 
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql # sql script to create tables
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql # sql script to fill tables

  productos:
    build:
      dockerfile: Dockerfile
      context: ./productos
    container_name: nodejs-microservice-productos
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - "postgres"
  
  carritos:
    build:
      dockerfile: Dockerfile
      context: ./carritos
    container_name: nodejs-microservice-carritos
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - "postgres"

  clientes:
    build:
      dockerfile: Dockerfile
      context: ./clientes
    container_name: nodejs-microservice-clientes
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - "postgres"

  ventas:
      build:
        dockerfile: Dockerfile
        context: ./ventas
      container_name: nodejs-microservice-ventas
      ports:
        - "3003:3003"
      restart: always
      depends_on:
        - "postgres"
    
volumes:
  postgres-data:
    driver: local
